import data from './commute-minutes.json';
import type { CommuteMinutes, NeighborhoodId } from './types';

// Side-loaded commute data, generated by `scripts/compute-commutes.mjs`.
// Kept separate from neighborhoods.ts because it's machine-generated and
// gets refreshed independently (re-run quarterly to absorb transit changes).
export const commuteMinutesByNeighborhood: Readonly<Record<NeighborhoodId, CommuteMinutes>> =
  data as Readonly<Record<NeighborhoodId, CommuteMinutes>>;

export function getCommuteMinutes(neighborhoodId: NeighborhoodId): CommuteMinutes {
  return commuteMinutesByNeighborhood[neighborhoodId] ?? {};
}
