import type { Neighborhood } from './types';

// Single-file POC content. Will split to one-file-per-neighborhood at v1.
// Scores are subjective editorial judgments. Each in [-1, 1].

export const neighborhoods: readonly Neighborhood[] = [
  // -------- MANHATTAN --------
  {
    id: 'upper-west-side', slug: 'upper-west-side', name: 'Upper West Side', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': -0.1, 'transit-psychology': 0.5, 'prestige-orientation': 0.5,
      'space-sensitivity': 0.5, 'family-trajectory': 0.8, 'cultural-ecosystem': 0.2,
      'environmental-openness': 0.8, 'creative-energy': 0.0, 'friction-sensitivity': 0.6,
      'safety-need': 0.8, 'school-quality': 0.85,
    },
    culturalTags: ['jewish'],
    housingTypes: ['co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'A grand pre-war neighborhood that has chosen to grow up. Tree-lined cross streets, classic apartment stock with real bedrooms, two parks bracketing the avenues, and three reliable subway lines. It reads as a permanent place to live, not a phase.',
      whoThrivesHere: 'Family-trajectory urbanists who want substance over scene.',
      tradeoffs: ['Quieter than you might want in your 20s', 'Real estate priced for stability, not value', 'Famously self-satisfied. Lean in or it grates.'],
    },
    anchors: { transit: ['1 train', '2/3 train', 'B/C train'], parks: ['Central Park', 'Riverside Park'], groceries: ['Zabar\'s', 'Citarella', 'Trader Joe\'s'] },
    heroImage: '/images/neighborhoods/upper-west-side.svg',
  },
  {
    id: 'upper-east-side', slug: 'upper-east-side', name: 'Upper East Side', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': 0.0, 'transit-psychology': 0.3, 'prestige-orientation': 0.7,
      'space-sensitivity': 0.4, 'family-trajectory': 0.7, 'cultural-ecosystem': 0.0,
      'environmental-openness': 0.7, 'creative-energy': -0.2, 'friction-sensitivity': 0.7,
      'safety-need': 0.85, 'school-quality': 0.85,
    },
    culturalTags: ['jewish'],
    housingTypes: ['townhouse', 'co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'Manhattan\'s most polished residential quadrant. Limestone, doormen, museums by the dozen, and a kind of orderly calm that no other part of the city quite produces. Transit is the catch. Historically Lex-only, the Q now helps.',
      whoThrivesHere: 'People who want the city\'s prestige without its grit.',
      tradeoffs: ['Q only goes so far. Lex is congested.', 'Energy is calm to the point of muted', 'Reads as conservative even when it isn\'t'],
    },
    anchors: { transit: ['4/5/6 train (Lex)', 'Q train (2nd Ave)'], parks: ['Central Park', 'Carl Schurz'], groceries: ['Agata & Valentina', 'Whole Foods', 'Eli\'s'] },
    heroImage: '/images/neighborhoods/upper-east-side.svg',
  },
  {
    id: 'west-village', slug: 'west-village', name: 'West Village', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': 0.3, 'transit-psychology': 0.5, 'prestige-orientation': 0.9,
      'space-sensitivity': -0.3, 'family-trajectory': 0.4, 'cultural-ecosystem': 0.2,
      'environmental-openness': 0.4, 'creative-energy': 0.5, 'friction-sensitivity': 0.4,
      'safety-need': 0.75, 'school-quality': 0.8,
    },
    culturalTags: ['lgbtq'],
    housingTypes: ['townhouse', 'co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'The most photographed neighborhood in NYC for a reason. Narrow streets at human scale, low-rise townhouses, restaurants that have been there for decades. Comes with the price tag and the tourists, but lived-in West Village is genuinely magical.',
      whoThrivesHere: 'Cosmopolitans who want a postcard street and don\'t flinch at the cost.',
      tradeoffs: ['Tourist load is real on weekends', 'Apartments are small for the price', 'Quieter than the East Village. Some find it too settled.'],
    },
    anchors: { transit: ['1 train', 'A/C/E', 'L', 'PATH (14th)'], parks: ['Hudson River Park', 'Washington Square'], groceries: ['Citarella', 'Mr. Bing\'s', 'Whole Foods (14th)'] },
    heroImage: '/images/neighborhoods/west-village.svg',
  },
  {
    id: 'east-village', slug: 'east-village', name: 'East Village', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': 0.7, 'transit-psychology': 0.0, 'prestige-orientation': 0.0,
      'space-sensitivity': -0.4, 'family-trajectory': -0.4, 'cultural-ecosystem': 0.5,
      'environmental-openness': 0.0, 'creative-energy': 0.7, 'friction-sensitivity': -0.4,
      'safety-need': 0.55, 'school-quality': 0.5,
    },
    housingTypes: ['co-op', 'rental'],
    basePassages: {
      whyItFits: 'Less polished than the West Village, more itself. Walk-up apartments, a dense lattice of bars and bookshops and small restaurants, the layered residue of every NYC subculture from the 60s onward. Energy is high. Orderliness is not the point.',
      whoThrivesHere: 'Creative immersionists in their 20s and 30s who want texture over polish.',
      tradeoffs: ['Subway access is awkward (just F at 2nd Ave)', 'Loud at night. Rage on Sunday morning.', 'Apartments are old and small'],
    },
    anchors: { transit: ['L (1st/3rd Ave)', 'F (2nd Ave)', '6 (Astor)'], parks: ['Tompkins Square'], groceries: ['Trader Joe\'s (14th)', 'Key Food', 'Westside Market'] },
    heroImage: '/images/neighborhoods/east-village.svg',
  },
  {
    id: 'tribeca', slug: 'tribeca', name: 'Tribeca', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': -0.1, 'transit-psychology': 0.6, 'prestige-orientation': 0.95,
      'space-sensitivity': 0.5, 'family-trajectory': 0.6, 'cultural-ecosystem': 0.0,
      'environmental-openness': 0.4, 'creative-energy': 0.3, 'friction-sensitivity': 0.7,
      'safety-need': 0.85, 'school-quality': 0.85,
    },
    housingTypes: ['condo', 'co-op', 'rental'],
    basePassages: {
      whyItFits: 'Cobbled streets, cast-iron buildings, lofts large enough to swing a piano in. Manhattan\'s priciest residential triangle by some measures, and the calm-with-cachet that price buys is real. Quiet on weekends, walking distance to the river, restaurants that don\'t need to advertise.',
      whoThrivesHere: 'Established families and creative-class veterans who want space without leaving downtown.',
      tradeoffs: ['Among the priciest per square foot in the city', 'Quiet on weekends to the point of empty', 'Schools are competitive entry points'],
    },
    anchors: { transit: ['1 train', '2/3', 'A/C/E', 'PATH (WTC)'], parks: ['Hudson River Park', 'Battery Park'], groceries: ['Whole Foods (Tribeca)', 'Bazzini', 'Eataly Downtown'] },
    heroImage: '/images/neighborhoods/tribeca.svg',
  },
  {
    id: 'fidi', slug: 'financial-district', name: 'Financial District', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': 0.2, 'transit-psychology': 0.8, 'prestige-orientation': 0.3,
      'space-sensitivity': 0.5, 'family-trajectory': 0.3, 'cultural-ecosystem': -0.2,
      'environmental-openness': 0.6, 'creative-energy': -0.2, 'friction-sensitivity': 0.5,
      'safety-need': 0.7, 'school-quality': 0.85,
    },
    housingTypes: ['condo', 'co-op', 'rental'],
    basePassages: {
      whyItFits: 'NYC\'s most transit-redundant residential zone. A dozen subway lines and the PATH inside a square mile, plus ferry. Newer apartment stock is generous on space relative to price. The waterfront promenade does most of what Riverside Park does, with bigger views.',
      whoThrivesHere: 'Transit-optimizers and value-conscious professionals willing to trade neighborhood texture for square footage.',
      tradeoffs: ['Empty on weekends. Restaurants close early.', 'Tourist crush around 9/11 Memorial', 'Lacks the texture of older Manhattan neighborhoods'],
    },
    anchors: { transit: ['Every line', 'PATH (WTC)', 'Ferry'], parks: ['Battery Park', 'Hudson River Park'], groceries: ['Whole Foods (Tribeca)', 'Eataly', 'Brookfield Place'] },
    heroImage: '/images/neighborhoods/financial-district.svg',
  },
  {
    id: 'chelsea', slug: 'chelsea', name: 'Chelsea', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': 0.4, 'transit-psychology': 0.7, 'prestige-orientation': 0.5,
      'space-sensitivity': 0.0, 'family-trajectory': 0.0, 'cultural-ecosystem': 0.2,
      'environmental-openness': 0.5, 'creative-energy': 0.6, 'friction-sensitivity': 0.0,
      'safety-need': 0.7, 'school-quality': 0.6,
    },
    culturalTags: ['lgbtq'],
    housingTypes: ['co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'A neighborhood that has reinvented itself more than once and lives at the intersection of art galleries, the High Line, the Hudson, Hudson Yards, and one of the city\'s great food halls. Flat and walkable, well-served by every cross-town option.',
      whoThrivesHere: 'People who want gallery culture and walkability without committing to a residential bubble.',
      tradeoffs: ['Tourists spike around the High Line', 'Hudson Yards has changed the western edge in mixed ways', 'Quieter at night than its reputation suggests'],
    },
    anchors: { transit: ['A/C/E', '1', 'L (8th)', '7 (Hudson Yards)'], parks: ['High Line', 'Chelsea Waterside', 'Hudson River Park'], groceries: ['Chelsea Market', 'Whole Foods', 'Trader Joe\'s'] },
    heroImage: '/images/neighborhoods/chelsea.svg',
  },
  {
    id: 'gramercy', slug: 'gramercy', name: 'Gramercy Park', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': -0.2, 'transit-psychology': 0.3, 'prestige-orientation': 0.7,
      'space-sensitivity': 0.4, 'family-trajectory': 0.5, 'cultural-ecosystem': -0.1,
      'environmental-openness': 0.3, 'creative-energy': 0.0, 'friction-sensitivity': 0.7,
      'safety-need': 0.8, 'school-quality': 0.7,
    },
    housingTypes: ['co-op', 'condo', 'townhouse', 'rental'],
    basePassages: {
      whyItFits: 'A pocket of unexpected calm right in midtown\'s belly, anchored by NYC\'s only private park. Pre-war buildings, low-rise blocks, and a settled-in feeling that contrasts with the energy three avenues in any direction.',
      whoThrivesHere: 'People who want central Manhattan\'s reach with residential calm.',
      tradeoffs: ['Subway access mediocre. Lex only.', 'Most of "the Park" is keyed to neighborhood residents', 'Niche enough that newcomers find it small'],
    },
    anchors: { transit: ['6 (23rd/28th)', 'L (Union Sq)', 'N/Q/R/W (Union Sq)'], parks: ['Madison Square', 'Union Square'], groceries: ['Trader Joe\'s', 'Whole Foods (Union Sq)'] },
    heroImage: '/images/neighborhoods/gramercy.svg',
  },
  {
    id: 'hells-kitchen', slug: 'hells-kitchen', name: 'Hell\'s Kitchen', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': 0.5, 'transit-psychology': 0.7, 'prestige-orientation': 0.0,
      'space-sensitivity': -0.2, 'family-trajectory': -0.2, 'cultural-ecosystem': 0.4,
      'environmental-openness': 0.2, 'creative-energy': 0.4, 'friction-sensitivity': -0.3,
      'safety-need': 0.6, 'school-quality': 0.55,
    },
    culturalTags: ['lgbtq'],
    housingTypes: ['co-op', 'rental'],
    basePassages: {
      whyItFits: 'NYC\'s most diverse restaurant row, walking distance to anywhere in midtown, and the most transit-redundant west-side residential zone. Loud, dense, and unpretentious. The un-glamorous engine room of central Manhattan life.',
      whoThrivesHere: 'High-energy professionals and theater-adjacent creative workers who want central without precious.',
      tradeoffs: ['Tourist crush near Times Square', 'Apartments mostly tenement-era walk-ups', 'Daily friction is high. Accept or move.'],
    },
    anchors: { transit: ['A/C/E', '1', 'N/Q/R/W', '7'], parks: ['Hudson River Park', 'DeWitt Clinton'], groceries: ['Whole Foods (Columbus)', 'Westerly', 'Stiles Farmers Market'] },
    heroImage: '/images/neighborhoods/hells-kitchen.svg',
  },
  {
    id: 'central-harlem', slug: 'central-harlem', name: 'Central Harlem', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': 0.3, 'transit-psychology': 0.5, 'prestige-orientation': -0.3,
      'space-sensitivity': 0.6, 'family-trajectory': 0.4, 'cultural-ecosystem': 0.7,
      'environmental-openness': 0.5, 'creative-energy': 0.4, 'friction-sensitivity': 0.0,
      'safety-need': 0.55, 'school-quality': 0.45,
    },
    culturalTags: ['african-american', 'west-african'],
    housingTypes: ['townhouse', 'co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'One of NYC\'s deepest cultural neighborhoods, with brownstone blocks the equal of anywhere in Brooklyn at notably lower per-square-foot prices. The 2/3 puts you in midtown faster than people assume.',
      whoThrivesHere: 'Value-conscious people who want space, history, and a real neighborhood.',
      tradeoffs: ['Block-by-block character variance is real', 'Restaurant scene is improving but uneven', 'Long perceived distance from the rest of Manhattan'],
    },
    anchors: { transit: ['2/3 train', 'B/C', 'A/D'], parks: ['Central Park (north)', 'Marcus Garvey'], groceries: ['Whole Foods (125th)', 'Trader Joe\'s'] },
    heroImage: '/images/neighborhoods/central-harlem.svg',
  },
  // -------- BROOKLYN --------
  {
    id: 'williamsburg', slug: 'williamsburg', name: 'Williamsburg', borough: 'brooklyn',
    scores: {
      'urban-intensity-tolerance': 0.5, 'transit-psychology': 0.0, 'prestige-orientation': 0.4,
      'space-sensitivity': 0.0, 'family-trajectory': 0.0, 'cultural-ecosystem': 0.3,
      'environmental-openness': 0.4, 'creative-energy': 0.7, 'friction-sensitivity': -0.2,
      'safety-need': 0.7, 'school-quality': 0.55,
    },
    housingTypes: ['condo', 'co-op', 'rental'],
    basePassages: {
      whyItFits: 'NYC\'s most successful gentrification arc, complete. The L holds the neighborhood hostage, but newer residential buildings are large and waterfront-adjacent, the restaurants are excellent, and the energy peaks higher than anywhere in Brooklyn except maybe Bushwick on a Saturday night.',
      whoThrivesHere: 'Creative-class people in their late 20s and 30s who want energy without committing to Manhattan prices.',
      tradeoffs: ['L train dependence is a real psychological burden', 'Has lost much of its grit. If that\'s what drew you, look further east.', 'Prices are now Manhattan-adjacent'],
    },
    anchors: { transit: ['L (Bedford/Lorimer)', 'G', 'J/M/Z (Marcy)', 'Ferry'], parks: ['Domino Park', 'McCarren', 'East River State'], groceries: ['Whole Foods', 'Trader Joe\'s', 'Brooklyn Harvest'] },
    heroImage: '/images/neighborhoods/williamsburg.svg',
  },
  {
    id: 'park-slope', slug: 'park-slope', name: 'Park Slope', borough: 'brooklyn',
    scores: {
      'urban-intensity-tolerance': -0.3, 'transit-psychology': 0.4, 'prestige-orientation': 0.5,
      'space-sensitivity': 0.5, 'family-trajectory': 0.95, 'cultural-ecosystem': 0.1,
      'environmental-openness': 0.8, 'creative-energy': 0.0, 'friction-sensitivity': 0.7,
      'safety-need': 0.85, 'school-quality': 0.9,
    },
    culturalTags: ['lgbtq', 'jewish'],
    housingTypes: ['townhouse', 'co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'Brownstone calm, leafy blocks, the Park literally there, and trains that put you in Manhattan in twenty minutes. Has become the platonic ideal of "where one moves when one has kids in NYC," for better and for worse.',
      whoThrivesHere: 'Future-family planners and couples looking for emotional sustainability over time.',
      tradeoffs: ['Quiet to the point of insular on weekends', 'Real estate priced like Manhattan. You\'re paying for the calm.', 'Limited late-night life'],
    },
    anchors: { transit: ['F/G', 'R', 'B/Q (Prospect Park)', '2/3 (Grand Army)'], parks: ['Prospect Park'], groceries: ['Union Market', 'Park Slope Food Coop', 'Key Food'] },
    heroImage: '/images/neighborhoods/park-slope.svg',
  },
  {
    id: 'brooklyn-heights', slug: 'brooklyn-heights', name: 'Brooklyn Heights', borough: 'brooklyn',
    scores: {
      'urban-intensity-tolerance': -0.4, 'transit-psychology': 0.7, 'prestige-orientation': 0.6,
      'space-sensitivity': 0.4, 'family-trajectory': 0.7, 'cultural-ecosystem': 0.0,
      'environmental-openness': 0.7, 'creative-energy': -0.1, 'friction-sensitivity': 0.8,
      'safety-need': 0.85, 'school-quality': 0.85,
    },
    housingTypes: ['townhouse', 'co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'Brooklyn\'s most architecturally serious residential neighborhood. Wide avenues of 19th-century townhouses, the Promenade with the most famous skyline view in the city, and transit redundancy that surprises people. Calm without being remote.',
      whoThrivesHere: 'Calm-seeking urbanists who want substance and a fast door back to Manhattan.',
      tradeoffs: ['Fewer restaurants than the buzzier Brooklyn neighborhoods', 'Quiet on weekends. More residential than alive.', 'Some of the most expensive blocks in Brooklyn'],
    },
    anchors: { transit: ['2/3', '4/5', 'R', 'A/C', 'F'], parks: ['Brooklyn Bridge Park', 'Cadman Plaza'], groceries: ['Trader Joe\'s', 'Key Food', 'Sahadi\'s'] },
    heroImage: '/images/neighborhoods/brooklyn-heights.svg',
  },
  {
    id: 'bed-stuy', slug: 'bed-stuy', name: 'Bed-Stuy', borough: 'brooklyn',
    scores: {
      'urban-intensity-tolerance': 0.2, 'transit-psychology': 0.4, 'prestige-orientation': -0.1,
      'space-sensitivity': 0.6, 'family-trajectory': 0.3, 'cultural-ecosystem': 0.5,
      'environmental-openness': 0.3, 'creative-energy': 0.5, 'friction-sensitivity': 0.0,
      'safety-need': 0.5, 'school-quality': 0.4,
    },
    culturalTags: ['african-american', 'caribbean'],
    housingTypes: ['townhouse', 'co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'Some of the most beautiful brownstone blocks in Brooklyn, a cultural depth that\'s been here longer than most of NYC\'s newer arrivals, and apartment values that still beat the prime areas. Has shifted significantly in the last decade and is still doing so.',
      whoThrivesHere: 'Value-and-space seekers who want a real neighborhood with history.',
      tradeoffs: ['A and C only. Train choice is limited.', 'Block-by-block variance', 'The gentrification arc is contested and ongoing'],
    },
    anchors: { transit: ['A/C', 'G', 'J/M/Z'], parks: ['Herbert Von King', 'Saratoga'], groceries: ['Foodtown', 'C-Town', 'Apollo'] },
    heroImage: '/images/neighborhoods/bed-stuy.svg',
  },
  {
    id: 'dumbo', slug: 'dumbo', name: 'DUMBO', borough: 'brooklyn',
    scores: {
      'urban-intensity-tolerance': 0.2, 'transit-psychology': 0.5, 'prestige-orientation': 0.7,
      'space-sensitivity': 0.4, 'family-trajectory': 0.3, 'cultural-ecosystem': 0.0,
      'environmental-openness': 0.7, 'creative-energy': 0.5, 'friction-sensitivity': 0.4,
      'safety-need': 0.8, 'school-quality': 0.7,
    },
    housingTypes: ['condo', 'co-op', 'rental'],
    basePassages: {
      whyItFits: 'Cobbled streets between two bridges, cast-iron warehouses converted to lofts, and direct access to one of the city\'s most spectacular waterfront parks. A small neighborhood with outsize cinematic identity.',
      whoThrivesHere: 'Design-and-tech professionals who want the waterfront as their daily backdrop.',
      tradeoffs: ['Very small footprint. Limited grocery, limited variety.', 'Tourist load is constant', 'Among the priciest per-square-foot in Brooklyn'],
    },
    anchors: { transit: ['F (York)', 'A/C (High St)', 'Ferry'], parks: ['Brooklyn Bridge Park'], groceries: ['Foragers', 'Empire Stores'] },
    heroImage: '/images/neighborhoods/dumbo.svg',
  },
  {
    id: 'cobble-hill', slug: 'cobble-hill', name: 'Cobble Hill', borough: 'brooklyn',
    scores: {
      'urban-intensity-tolerance': -0.3, 'transit-psychology': 0.5, 'prestige-orientation': 0.4,
      'space-sensitivity': 0.4, 'family-trajectory': 0.7, 'cultural-ecosystem': 0.2,
      'environmental-openness': 0.5, 'creative-energy': 0.0, 'friction-sensitivity': 0.7,
      'safety-need': 0.85, 'school-quality': 0.8,
    },
    culturalTags: ['middle-eastern'],
    housingTypes: ['townhouse', 'co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'A 12-block jewel between the BQE and Court Street: brownstones, low buildings, mature street trees, and one of the better residential restaurant rows in Brooklyn. Calm without feeling hidden. Atlantic Avenue still anchors the longstanding Arab-American community.',
      whoThrivesHere: 'Couples and early-family households who value scale and proximity equally.',
      tradeoffs: ['Quiet. Not the place for nightlife.', 'Real estate competitive', 'Trains all about a 10-minute walk'],
    },
    anchors: { transit: ['F/G (Bergen)', 'R (Court)', '2/3/4/5 (Borough Hall)'], parks: ['Cobble Hill Park', 'Brooklyn Bridge Park'], groceries: ['Trader Joe\'s', 'Sahadi\'s', 'Union Market'] },
    heroImage: '/images/neighborhoods/cobble-hill.svg',
  },
  {
    id: 'bushwick', slug: 'bushwick', name: 'Bushwick', borough: 'brooklyn',
    scores: {
      'urban-intensity-tolerance': 0.6, 'transit-psychology': 0.0, 'prestige-orientation': -0.4,
      'space-sensitivity': 0.5, 'family-trajectory': -0.3, 'cultural-ecosystem': 0.5,
      'environmental-openness': -0.1, 'creative-energy': 0.8, 'friction-sensitivity': -0.5,
      'safety-need': 0.45, 'school-quality': 0.35,
    },
    culturalTags: ['latin-american'],
    housingTypes: ['condo', 'rental'],
    basePassages: {
      whyItFits: 'Brooklyn\'s current creative engine room. Converted lofts, warehouse parties, mural-walled industrial blocks, and the largest concentration of working artists in NYC. Apartments are still relatively large for the price. The L is your lifeline.',
      whoThrivesHere: 'Creative immersionists in their 20s and 30s who want to be near scene and accept the friction that comes with it.',
      tradeoffs: ['L-train dependence', 'Daily friction is high. Gritty by design.', 'Block-by-block safety perception varies'],
    },
    anchors: { transit: ['L (Morgan/Jefferson/DeKalb)', 'M (Myrtle)', 'J/Z'], parks: ['Maria Hernandez', 'Bushwick Inlet (a stretch)'], groceries: ['Trader Joe\'s (nearby)', 'Mr. Kiwi', 'Western Beef'] },
    heroImage: '/images/neighborhoods/bushwick.svg',
  },
  {
    id: 'brighton-beach', slug: 'brighton-beach', name: 'Brighton Beach', borough: 'brooklyn',
    scores: {
      'urban-intensity-tolerance': 0.3, 'transit-psychology': 0.0, 'prestige-orientation': -0.5,
      'space-sensitivity': 0.5, 'family-trajectory': 0.5, 'cultural-ecosystem': 0.95,
      'environmental-openness': 0.7, 'creative-energy': 0.0, 'friction-sensitivity': -0.1,
      'safety-need': 0.6, 'school-quality': 0.5,
    },
    culturalTags: ['eastern-european'],
    housingTypes: ['co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'The deepest Russian and Ukrainian community in the country, on a literal beach, with a boardwalk that gets you out of the city without leaving it. The Q is a long ride to Manhattan but a quiet one. Apartments cost a fraction of prime Brooklyn.',
      whoThrivesHere: 'Cultural-anchor seekers, especially those for whom post-Soviet community is daily life.',
      tradeoffs: ['End of the Q line means a real commute', 'Reads as far from "the city" even when it isn\'t in time', 'Limited beyond the cultural and beach scene'],
    },
    anchors: { transit: ['Q (terminus)', 'B (rush hours)'], parks: ['Brighton Beach Boardwalk', 'Coney Island Beach'], groceries: ['Brighton Bazaar', 'Net Cost Market', 'M&I International'] },
    heroImage: '/images/neighborhoods/brighton-beach.svg',
  },
  {
    id: 'sheepshead-bay', slug: 'sheepshead-bay', name: 'Sheepshead Bay', borough: 'brooklyn',
    scores: {
      'urban-intensity-tolerance': 0.0, 'transit-psychology': 0.3, 'prestige-orientation': -0.4,
      'space-sensitivity': 0.7, 'family-trajectory': 0.6, 'cultural-ecosystem': 0.7,
      'environmental-openness': 0.6, 'creative-energy': -0.2, 'friction-sensitivity': 0.4,
      'safety-need': 0.65, 'school-quality': 0.55,
    },
    culturalTags: ['eastern-european', 'east-asian'],
    housingTypes: ['single-family', 'co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'A genuine waterfront community, less famous than Brighton but materially better-served by transit (B and Q). Apartment stock includes real two-bedrooms at prices Brooklyn proper has forgotten. A working mix of Russian, Chinese, Italian, and Caribbean communities.',
      whoThrivesHere: 'Value-and-space seekers who want a real neighborhood at south-Brooklyn prices.',
      tradeoffs: ['Long commute to Manhattan', 'Limited dining/nightlife at the high end', 'Reads as "deep Brooklyn" to Manhattanites'],
    },
    anchors: { transit: ['B', 'Q', 'B36/B49 buses'], parks: ['Sheepshead Bay waterfront', 'Marine Park nearby'], groceries: ['Net Cost', 'Stop & Shop', 'Brighton Bazaar nearby'] },
    heroImage: '/images/neighborhoods/sheepshead-bay.svg',
  },
  // -------- QUEENS --------
  {
    id: 'long-island-city', slug: 'long-island-city', name: 'Long Island City', borough: 'queens',
    scores: {
      'urban-intensity-tolerance': 0.2, 'transit-psychology': 0.7, 'prestige-orientation': 0.2,
      'space-sensitivity': 0.6, 'family-trajectory': 0.5, 'cultural-ecosystem': 0.2,
      'environmental-openness': 0.7, 'creative-energy': 0.3, 'friction-sensitivity': 0.5,
      'safety-need': 0.75, 'school-quality': 0.55,
    },
    housingTypes: ['condo', 'rental'],
    basePassages: {
      whyItFits: 'A new high-rise riverfront with one of NYC\'s best skyline views from your living room. Newer apartment stock means real space. Transit redundancy is genuinely strong (7, E, M, G, F, plus ferry). Waterfront parks anchor the daily walk.',
      whoThrivesHere: 'Value-aware urbanists who want space, transit, and views without leaving the inner city.',
      tradeoffs: ['New-build energy can feel anonymous', 'Restaurant scene is uneven outside of Vernon-Jackson', 'Far from the cultural texture of older Queens'],
    },
    anchors: { transit: ['7', 'E/M (Court Sq)', 'G', 'F (21st)', 'Ferry'], parks: ['Gantry Plaza State Park', 'Hunter\'s Point South'], groceries: ['Food Cellar', 'Trader Joe\'s (nearby)'] },
    heroImage: '/images/neighborhoods/long-island-city.svg',
  },
  {
    id: 'astoria', slug: 'astoria', name: 'Astoria', borough: 'queens',
    scores: {
      'urban-intensity-tolerance': 0.1, 'transit-psychology': 0.5, 'prestige-orientation': -0.1,
      'space-sensitivity': 0.6, 'family-trajectory': 0.5, 'cultural-ecosystem': 0.7,
      'environmental-openness': 0.4, 'creative-energy': 0.3, 'friction-sensitivity': 0.4,
      'safety-need': 0.75, 'school-quality': 0.65,
    },
    culturalTags: ['mediterranean', 'middle-eastern'],
    housingTypes: ['townhouse', 'co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'NYC\'s deepest Greek neighborhood and one of its most successfully diverse, with apartments materially larger than equivalent prices in Brooklyn. The N/W gives you direct midtown access. Daily life is anchored by restaurants from a dozen cuisines within walking distance.',
      whoThrivesHere: 'Cultural-anchor seekers and value-seeking professionals.',
      tradeoffs: ['Restaurant scene is famous. Nightlife less so.', 'N/W can be slow off-peak', 'Walking distance varies greatly by block'],
    },
    anchors: { transit: ['N/W', 'R (Steinway)', 'M (Steinway)', 'F (nearby)'], parks: ['Astoria Park', 'Socrates Sculpture Park'], groceries: ['Trade Fair', 'Key Food', 'Mediterranean Foods'] },
    heroImage: '/images/neighborhoods/astoria.svg',
  },
  {
    id: 'flushing', slug: 'flushing', name: 'Flushing', borough: 'queens',
    scores: {
      'urban-intensity-tolerance': 0.5, 'transit-psychology': 0.3, 'prestige-orientation': -0.3,
      'space-sensitivity': 0.5, 'family-trajectory': 0.6, 'cultural-ecosystem': 0.95,
      'environmental-openness': 0.4, 'creative-energy': 0.0, 'friction-sensitivity': -0.3,
      'safety-need': 0.6, 'school-quality': 0.7,
    },
    culturalTags: ['east-asian'],
    housingTypes: ['single-family', 'co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'NYC\'s densest pan-Asian neighborhood and one of the country\'s great food cities in its own right. Apartments are larger and cheaper than anywhere comparable. The 7 train is your direct line to midtown.',
      whoThrivesHere: 'Cultural-anchor seekers, particularly those for whom East Asian community access is daily life.',
      tradeoffs: ['Very crowded and high-friction at street level', '7 train is the only real subway option', 'Far from Manhattan in feel even when it isn\'t in time'],
    },
    anchors: { transit: ['7 (terminus)', 'LIRR'], parks: ['Flushing Meadows-Corona Park', 'Kissena'], groceries: ['H Mart', 'New World Mall', 'Skyfoods'] },
    heroImage: '/images/neighborhoods/flushing.svg',
  },
  {
    id: 'forest-hills', slug: 'forest-hills', name: 'Forest Hills', borough: 'queens',
    scores: {
      'urban-intensity-tolerance': -0.3, 'transit-psychology': 0.4, 'prestige-orientation': 0.1,
      'space-sensitivity': 0.7, 'family-trajectory': 0.8, 'cultural-ecosystem': 0.3,
      'environmental-openness': 0.6, 'creative-energy': -0.3, 'friction-sensitivity': 0.7,
      'safety-need': 0.85, 'school-quality': 0.85,
    },
    culturalTags: ['jewish', 'eastern-european'],
    housingTypes: ['single-family', 'co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'The original planned NYC suburb-within-the-city, complete with Tudor-style buildings and tree-lined streets. Apartments are notably larger than anywhere comparable in Brooklyn or Manhattan. The E, F, M, R put you in midtown in 30-35 min. Strong Bukharian Jewish and Russian communities anchor daily life.',
      whoThrivesHere: 'Family-trajectory pragmatists who want suburban scale without leaving the city.',
      tradeoffs: ['Lower urban energy than newer arrivals expect', 'Limited dining/nightlife relative to Brooklyn', 'Commute is real (30+ min into Manhattan)'],
    },
    anchors: { transit: ['E/F/M/R', 'LIRR'], parks: ['Forest Park', 'Flushing Meadows nearby'], groceries: ['Trader Joe\'s (nearby Rego)', 'Key Food', 'Natural Frontier'] },
    heroImage: '/images/neighborhoods/forest-hills.svg',
  },
  // -------- BRONX --------
  {
    id: 'riverdale', slug: 'riverdale', name: 'Riverdale', borough: 'bronx',
    scores: {
      'urban-intensity-tolerance': -0.7, 'transit-psychology': -0.2, 'prestige-orientation': 0.0,
      'space-sensitivity': 0.8, 'family-trajectory': 0.85, 'cultural-ecosystem': 0.2,
      'environmental-openness': 0.9, 'creative-energy': -0.5, 'friction-sensitivity': 0.85,
      'safety-need': 0.85, 'school-quality': 0.85,
    },
    culturalTags: ['jewish'],
    carDependent: true,
    housingTypes: ['single-family', 'townhouse', 'co-op', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'A leafy, hilly, suburban-feeling pocket of NYC with Hudson views and apartment values that beat anything comparable on the other side of the bridge. The 1 train and Metro-North are the connections. The daily quiet is the point.',
      whoThrivesHere: 'Family-first households who want green space and quiet streets within city limits.',
      tradeoffs: ['Far from Manhattan. 1 train is slow, Metro-North requires planning.', 'Limited dining/nightlife', 'Car becomes useful, which is unusual for NYC'],
    },
    anchors: { transit: ['1 (Van Cortlandt)', 'Metro-North (Hudson Line)'], parks: ['Van Cortlandt Park', 'Wave Hill', 'Hudson waterfront'], groceries: ['Skyview Center', 'Stop & Shop', 'Riverdale Garden Market'] },
    heroImage: '/images/neighborhoods/riverdale.svg',
  },
  // -------- STATEN ISLAND --------
  {
    id: 'st-george', slug: 'st-george', name: 'St. George', borough: 'staten-island',
    scores: {
      'urban-intensity-tolerance': -0.3, 'transit-psychology': 0.0, 'prestige-orientation': -0.4,
      'space-sensitivity': 0.7, 'family-trajectory': 0.5, 'cultural-ecosystem': 0.3,
      'environmental-openness': 0.7, 'creative-energy': -0.2, 'friction-sensitivity': 0.6,
      'safety-need': 0.6, 'school-quality': 0.5,
    },
    housingTypes: ['single-family', 'townhouse', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'The only NYC neighborhood with a five-minute walk to a free 25-minute ferry to Lower Manhattan. Apartments are dramatically larger and cheaper than anywhere on the other end of that ferry. Views are the daily reward.',
      whoThrivesHere: 'Value-and-space seekers who genuinely don\'t mind the ferry rhythm.',
      tradeoffs: ['Ferry is the lifeline. If it breaks, your day breaks.', 'Limited nightlife and dining outside Bay Street', 'Staten Island can feel disconnected from the rest of NYC culture'],
    },
    anchors: { transit: ['Staten Island Ferry', 'SI Railway'], parks: ['Snug Harbor', 'Tompkinsville Park'], groceries: ['Western Beef', 'Trader Joe\'s (nearby)'] },
    heroImage: '/images/neighborhoods/st-george.svg',
  },
  // -------- NJ --------
  {
    id: 'hoboken', slug: 'hoboken', name: 'Hoboken', borough: 'nj',
    scores: {
      'urban-intensity-tolerance': 0.0, 'transit-psychology': 0.6, 'prestige-orientation': 0.2,
      'space-sensitivity': 0.5, 'family-trajectory': 0.7, 'cultural-ecosystem': 0.0,
      'environmental-openness': 0.6, 'creative-energy': 0.0, 'friction-sensitivity': 0.5,
      'safety-need': 0.85, 'school-quality': 0.7,
    },
    housingTypes: ['townhouse', 'condo', 'co-op', 'rental'],
    basePassages: {
      whyItFits: 'A walkable mile-square city across the river with PATH service that beats most subway commutes from outer Brooklyn. Apartments are larger, the waterfront promenade is genuinely beautiful, and Manhattan is closer in time than most of Queens.',
      whoThrivesHere: 'Future-family households and value-conscious professionals who want city scale at lower cost.',
      tradeoffs: ['Reads as suburban to NYC purists', 'Nightlife concentrated and college-aged in places', 'NJ logistics (taxes, paperwork) are different'],
    },
    anchors: { transit: ['PATH (Hoboken)', 'NJ Transit', 'Ferry'], parks: ['Pier A Park', 'Hoboken waterfront'], groceries: ['Trader Joe\'s', 'ShopRite', 'Whole Foods (nearby)'] },
    heroImage: '/images/neighborhoods/hoboken.svg',
  },
  {
    id: 'jersey-city', slug: 'jersey-city', name: 'Jersey City', borough: 'nj',
    scores: {
      'urban-intensity-tolerance': 0.3, 'transit-psychology': 0.7, 'prestige-orientation': 0.1,
      'space-sensitivity': 0.7, 'family-trajectory': 0.7, 'cultural-ecosystem': 0.4,
      'environmental-openness': 0.5, 'creative-energy': 0.2, 'friction-sensitivity': 0.4,
      'safety-need': 0.7, 'school-quality': 0.65,
    },
    culturalTags: ['south-asian', 'latin-american'],
    housingTypes: ['townhouse', 'condo', 'co-op', 'rental'],
    basePassages: {
      whyItFits: 'NJ\'s answer to LIC: high-rise waterfront with skyline views, several PATH stops giving direct Manhattan access, and a downtown that\'s diversified well beyond the original financial-services pitch. Materially more space per dollar than Manhattan.',
      whoThrivesHere: 'Value-aware urbanists, including dual-income couples and early-family households.',
      tradeoffs: ['NYC purists treat NJ as a different planet', 'Beyond downtown, transit gets car-dependent quickly', 'Tax structure requires its own homework'],
    },
    anchors: { transit: ['PATH (Exchange Place, Grove St, Newport)', 'Light Rail', 'Ferry'], parks: ['Liberty State Park', 'Newport Green', 'Hamilton Park'], groceries: ['ShopRite', 'Trader Joe\'s', 'Whole Foods'] },
    heroImage: '/images/neighborhoods/jersey-city.svg',
  },
  {
    id: 'fort-lee', slug: 'fort-lee', name: 'Fort Lee', borough: 'nj',
    scores: {
      'urban-intensity-tolerance': 0.0, 'transit-psychology': 0.5, 'prestige-orientation': 0.1,
      'space-sensitivity': 0.6, 'family-trajectory': 0.7, 'cultural-ecosystem': 0.6,
      'environmental-openness': 0.6, 'creative-energy': -0.1, 'friction-sensitivity': 0.6,
      'safety-need': 0.8, 'school-quality': 0.85,
    },
    culturalTags: ['east-asian'],
    carDependent: true,
    housingTypes: ['single-family', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'A serious Korean American center with cliffside views over the Hudson, real high-rise apartment stock, and quick bus access through the Lincoln Tunnel or over the GW Bridge. Schools are strong, restaurants are excellent, and apartments are bigger than NYC at meaningful margins.',
      whoThrivesHere: 'East Asian community-oriented households and value-conscious families willing to cross the river.',
      tradeoffs: ['No subway. Bus and car are the main connections.', 'Reads "very NJ" to NYC purists', 'Nightlife is limited compared to even outer Brooklyn'],
    },
    anchors: { transit: ['NJ Transit bus (Lincoln Tunnel)', 'GW Bridge buses', 'Ferry from Edgewater nearby'], parks: ['Palisades Interstate Park', 'Constitution Park'], groceries: ['H Mart', 'Costco (nearby)', 'Hannah\'s Korean Market'] },
    heroImage: '/images/neighborhoods/fort-lee.svg',
  },
  {
    id: 'edgewater', slug: 'edgewater', name: 'Edgewater', borough: 'nj',
    scores: {
      'urban-intensity-tolerance': -0.1, 'transit-psychology': 0.2, 'prestige-orientation': 0.1,
      'space-sensitivity': 0.6, 'family-trajectory': 0.6, 'cultural-ecosystem': 0.4,
      'environmental-openness': 0.7, 'creative-energy': -0.2, 'friction-sensitivity': 0.7,
      'safety-need': 0.8, 'school-quality': 0.75,
    },
    culturalTags: ['east-asian'],
    carDependent: true,
    housingTypes: ['condo', 'townhouse', 'rental'],
    basePassages: {
      whyItFits: 'A quiet waterfront strip with newer luxury developments, Korean and Japanese groceries within walking distance, and ferry service that beats driving into Manhattan. Apartments are big, parking is easy, and the Hudson is your front yard.',
      whoThrivesHere: 'Households who want waterfront space and a low-friction daily life within striking distance of NYC.',
      tradeoffs: ['Transit options are limited (ferry + buses)', 'Car becomes useful or necessary', 'Very residential, light on street life'],
    },
    anchors: { transit: ['NY Waterway Ferry', 'NJ Transit bus', 'Lincoln Tunnel buses'], parks: ['Veterans Field', 'Hudson waterfront promenade'], groceries: ['Mitsuwa Marketplace', 'Trader Joe\'s', 'Whole Foods'] },
    heroImage: '/images/neighborhoods/edgewater.svg',
  },
  {
    id: 'palisades-park', slug: 'palisades-park', name: 'Palisades Park', borough: 'nj',
    scores: {
      'urban-intensity-tolerance': 0.1, 'transit-psychology': 0.3, 'prestige-orientation': -0.1,
      'space-sensitivity': 0.5, 'family-trajectory': 0.65, 'cultural-ecosystem': 0.85,
      'environmental-openness': 0.4, 'creative-energy': -0.2, 'friction-sensitivity': 0.4,
      'safety-need': 0.75, 'school-quality': 0.75,
    },
    culturalTags: ['east-asian'],
    carDependent: true,
    housingTypes: ['single-family', 'condo', 'rental'],
    basePassages: {
      whyItFits: 'One of the densest Korean American communities in the United States. Broad Avenue is a working Korean main street: bakeries, banks, restaurants, banh-shop after banh-shop. Buses connect to Manhattan. The community itself is the reason to live here.',
      whoThrivesHere: 'Korean American households and others for whom East Asian community access is daily life.',
      tradeoffs: ['No subway access. Buses to NYC are the option.', 'Less waterfront-pretty than Edgewater', 'Reads "second-tier NJ" to NYC purists'],
    },
    anchors: { transit: ['NJ Transit bus (Broad Ave)', 'GW Bridge bus'], parks: ['Palisades Interstate Park nearby', 'Garibaldi Park'], groceries: ['H Mart', 'Hannah\'s', 'Han Yang'] },
    heroImage: '/images/neighborhoods/palisades-park.svg',
  },
  // -------- MANHATTAN (round 2 additions) --------
  {
    id: 'lower-east-side', slug: 'lower-east-side', name: 'Lower East Side', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': 0.6, 'transit-psychology': 0.4, 'prestige-orientation': 0.1,
      'space-sensitivity': -0.3, 'family-trajectory': -0.2, 'cultural-ecosystem': 0.6,
      'environmental-openness': 0.0, 'creative-energy': 0.7, 'friction-sensitivity': -0.3,
      'safety-need': 0.55, 'school-quality': 0.5,
    },
    culturalTags: ['jewish', 'east-asian'],
    housingTypes: ['co-op', 'rental', 'condo'],
    basePassages: {
      whyItFits: 'NYC\'s most layered neighborhood, with Jewish, Chinese, Puerto Rican, and Bangladeshi histories overlapping in the same blocks. Tenement walk-ups, gallery basements, music venues that have been there for decades. Loud, dense, and unapologetically itself.',
      whoThrivesHere: 'Creative-class people who want texture, history, and proximity to scene.',
      tradeoffs: ['Loud and crowded on weekend nights', 'Apartment stock is mostly old walk-ups', 'F is the main subway access; reaching the West Side takes effort'],
    },
    anchors: { transit: ['F (Delancey)', 'J/M/Z (Essex)', 'B/D (Grand)'], parks: ['Sara D. Roosevelt', 'East River Park'], groceries: ['Essex Market', 'Trader Joe\'s (nearby)', 'Whole Foods (Bowery)'] },
    heroImage: '/images/neighborhoods/lower-east-side.svg',
  },
  {
    id: 'east-harlem', slug: 'east-harlem', name: 'East Harlem', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': 0.4, 'transit-psychology': 0.4, 'prestige-orientation': -0.4,
      'space-sensitivity': 0.5, 'family-trajectory': 0.5, 'cultural-ecosystem': 0.85,
      'environmental-openness': 0.5, 'creative-energy': 0.3, 'friction-sensitivity': 0.0,
      'safety-need': 0.55, 'school-quality': 0.45,
    },
    culturalTags: ['latin-american', 'african-american'],
    housingTypes: ['rental', 'co-op', 'condo'],
    basePassages: {
      whyItFits: 'El Barrio. The deepest Puerto Rican community in NYC, with a Mexican and African-American cultural layer on top. Murals, mom-and-pop restaurants, real apartment values that beat the rest of Manhattan, and Central Park as your eastern edge.',
      whoThrivesHere: 'Cultural-anchor seekers and value-conscious people who want Manhattan space.',
      tradeoffs: ['Public transit is mostly the 4/5/6 (Lex)', 'Block-by-block character variance', 'Schools are improving but uneven'],
    },
    anchors: { transit: ['4/5/6 (Lex)', '2/3 (nearby)', 'M15 SBS bus'], parks: ['Central Park (north)', 'Thomas Jefferson Park'], groceries: ['Costco (nearby)', 'Fine Fare', 'La Marqueta'] },
    heroImage: '/images/neighborhoods/east-harlem.svg',
  },
  {
    id: 'hamilton-heights', slug: 'hamilton-heights', name: 'Hamilton Heights', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': 0.1, 'transit-psychology': 0.4, 'prestige-orientation': -0.1,
      'space-sensitivity': 0.7, 'family-trajectory': 0.5, 'cultural-ecosystem': 0.75,
      'environmental-openness': 0.7, 'creative-energy': 0.5, 'friction-sensitivity': 0.5,
      'safety-need': 0.65, 'school-quality': 0.55,
    },
    culturalTags: ['african-american', 'latin-american'],
    housingTypes: ['co-op', 'townhouse', 'rental'],
    basePassages: {
      whyItFits: 'Sugar Hill\'s historic-Black-NYC heart, hilltop views over the Hudson, and pre-war apartments with real bedrooms at notably lower per-square-foot prices than midtown. The 1 train and A express both serve it. City College is the institutional anchor.',
      whoThrivesHere: 'Value-and-space seekers who want history and a real neighborhood.',
      tradeoffs: ['Long perceived distance from downtown — though the A is fast', 'Restaurant scene is improving but uneven', 'Hilly enough that the walk home matters'],
    },
    anchors: { transit: ['1 (137th–145th)', 'A express (145th)', 'B/C (135th–145th)'], parks: ['Riverside Park', 'St. Nicholas Park'], groceries: ['Trader Joe\'s (nearby)', 'Fine Fare', 'Garden of Eden'] },
    heroImage: '/images/neighborhoods/hamilton-heights.svg',
  },
  {
    id: 'washington-heights', slug: 'washington-heights', name: 'Washington Heights', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': 0.0, 'transit-psychology': 0.3, 'prestige-orientation': -0.4,
      'space-sensitivity': 0.7, 'family-trajectory': 0.6, 'cultural-ecosystem': 0.85,
      'environmental-openness': 0.7, 'creative-energy': 0.0, 'friction-sensitivity': 0.4,
      'safety-need': 0.55, 'school-quality': 0.5,
    },
    culturalTags: ['latin-american'],
    housingTypes: ['co-op', 'rental', 'condo'],
    basePassages: {
      whyItFits: 'The largest Dominican community in the United States, on a hilltop with the George Washington Bridge as your view. Real pre-war apartments with closets and original details at prices that beat anywhere comparable in the rest of Manhattan. The A express runs from 168th to midtown faster than people expect.',
      whoThrivesHere: 'Value-and-space seekers, families, and culturally-anchored Latin households.',
      tradeoffs: ['Long perceived distance from midtown — actual time is moderate', 'A express is your express; locals are slow', 'Block-by-block variance is real'],
    },
    anchors: { transit: ['A express (175th, 181st)', '1 (157th–191st)', 'GWB bus terminal'], parks: ['Fort Tryon Park', 'Highbridge Park', 'Hudson waterfront'], groceries: ['Trader Joe\'s (nearby Inwood)', 'Fine Fare', 'Frank\'s Market'] },
    heroImage: '/images/neighborhoods/washington-heights.svg',
  },
  {
    id: 'inwood', slug: 'inwood', name: 'Inwood', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': -0.4, 'transit-psychology': 0.0, 'prestige-orientation': -0.5,
      'space-sensitivity': 0.8, 'family-trajectory': 0.7, 'cultural-ecosystem': 0.6,
      'environmental-openness': 0.95, 'creative-energy': 0.0, 'friction-sensitivity': 0.6,
      'safety-need': 0.6, 'school-quality': 0.55,
    },
    culturalTags: ['latin-american'],
    housingTypes: ['co-op', 'rental'],
    basePassages: {
      whyItFits: 'Manhattan\'s northern tip, with Inwood Hill Park\'s actual old-growth forest two blocks from your door. Pre-war apartments are huge and affordable; the 1 and A both end here. Dominican community is strong; the cultural texture is layered.',
      whoThrivesHere: 'Nature-hungry urbanists and value-seekers willing to trade commute time for park-side life.',
      tradeoffs: ['1 and A only — and you\'re at the end of the lines', '40+ minutes to midtown', 'Limited dining and nightlife'],
    },
    anchors: { transit: ['A (terminus, 207th)', '1 (215th, Dyckman)', 'M100/M101 buses'], parks: ['Inwood Hill Park', 'Fort Tryon Park (south edge)'], groceries: ['Frank\'s Market', 'Fine Fare', 'Inwood Farmers Market'] },
    heroImage: '/images/neighborhoods/inwood.svg',
  },
  {
    id: 'morningside-heights', slug: 'morningside-heights', name: 'Morningside Heights', borough: 'manhattan',
    scores: {
      'urban-intensity-tolerance': -0.2, 'transit-psychology': 0.3, 'prestige-orientation': 0.4,
      'space-sensitivity': 0.5, 'family-trajectory': 0.5, 'cultural-ecosystem': 0.3,
      'environmental-openness': 0.6, 'creative-energy': 0.3, 'friction-sensitivity': 0.5,
      'safety-need': 0.6, 'school-quality': 0.65,
    },
    housingTypes: ['co-op', 'rental'],
    basePassages: {
      whyItFits: 'Columbia\'s home neighborhood, with the Cathedral of St. John the Divine, Riverside Park to the west, and Morningside Park to the east. Pre-war apartments with academic-grade pricing. Quieter and more cerebral than the rest of the Upper West.',
      whoThrivesHere: 'Academic-leaning households and people who want institutional anchor with park access.',
      tradeoffs: ['Quiet to the point of subdued in summer when students are gone', 'Restaurant scene is improving but uneven', '1 train is the main subway'],
    },
    anchors: { transit: ['1 (110th–125th)', 'B/C (110th–116th)'], parks: ['Riverside Park', 'Morningside Park'], groceries: ['Whole Foods (Columbus)', 'Westside Market', 'Trader Joe\'s (nearby)'] },
    heroImage: '/images/neighborhoods/morningside-heights.svg',
  },
] as const;

export function neighborhoodById(id: string): Neighborhood | undefined {
  return neighborhoods.find((n) => n.id === id);
}

export function neighborhoodBySlug(slug: string): Neighborhood | undefined {
  return neighborhoods.find((n) => n.slug === slug);
}
