import calmSeekingUrbanist from './passages/calm-seeking-urbanist.json';
import creativeImmersionist from './passages/creative-immersionist.json';
import culturalAnchorSeeker from './passages/cultural-anchor-seeker.json';
import energyDrivenMaximalist from './passages/energy-driven-maximalist.json';
import familyTrajectoryPragmatist from './passages/family-trajectory-pragmatist.json';
import natureHungryUrbanist from './passages/nature-hungry-urbanist.json';
import prestigeAnchoredCosmopolitan from './passages/prestige-anchored-cosmopolitan.json';
import valueSeekingRooter from './passages/value-seeking-rooter.json';

import type { ArchetypeId, NeighborhoodId, Passage } from './types';

// Generated by scripts/generate-passages.ts via Claude API. Each entry is the
// archetype-specific take on a neighborhood: why it does (or doesn't) fit, and
// the tradeoffs THIS archetype would feel. ~904 passages total (8 × 113).
//
// Re-run the script to refresh; per-archetype JSON files mean a single
// archetype can be regenerated without disturbing the others.

type RawPassage = {
  fitProse: string;
  tradeoffsForYou: string[];
  reviewedAt: string | null;
  reviewedBy: string | null;
  generatedAt?: string;
  model?: string;
};

const passagesByArchetype: Record<ArchetypeId, Record<NeighborhoodId, RawPassage>> = {
  'calm-seeking-urbanist': calmSeekingUrbanist as Record<string, RawPassage>,
  'creative-immersionist': creativeImmersionist as Record<string, RawPassage>,
  'cultural-anchor-seeker': culturalAnchorSeeker as Record<string, RawPassage>,
  'energy-driven-maximalist': energyDrivenMaximalist as Record<string, RawPassage>,
  'family-trajectory-pragmatist': familyTrajectoryPragmatist as Record<string, RawPassage>,
  'nature-hungry-urbanist': natureHungryUrbanist as Record<string, RawPassage>,
  'prestige-anchored-cosmopolitan': prestigeAnchoredCosmopolitan as Record<string, RawPassage>,
  'value-seeking-rooter': valueSeekingRooter as Record<string, RawPassage>,
};

export function getPassage(
  archetypeId: ArchetypeId,
  neighborhoodId: NeighborhoodId,
): Passage | undefined {
  const raw = passagesByArchetype[archetypeId]?.[neighborhoodId];
  if (!raw) return undefined;
  return {
    archetypeId,
    neighborhoodId,
    fitProse: raw.fitProse,
    tradeoffsForYou: raw.tradeoffsForYou,
    reviewedAt: raw.reviewedAt,
    reviewedBy: raw.reviewedBy,
  };
}
