import type { Question } from './types';

export const questions: readonly Question[] = [
  {
    id: 'transit-redundancy',
    kind: 'forced_choice',
    prompt: 'How do you mostly want to get around?',
    choices: [
      {
        label: 'I\'d take transit. I want multiple options.',
        impacts: { 'transit-psychology': 0.7 },
      },
      {
        label: 'I\'d take transit. One reliable line is enough.',
        impacts: { 'transit-psychology': -0.3 },
      },
      {
        label: 'I\'d drive. Car-dependent is fine.',
        impacts: { 'transit-psychology': -0.7, 'urban-intensity-tolerance': -0.3 },
      },
    ],
  },
  {
    id: 'prestige-vs-space',
    kind: 'forced_choice',
    prompt: 'Smaller apartment in a famous neighborhood, or materially more space in a less-known one?',
    choices: [
      {
        label: 'The famous neighborhood. The address matters.',
        impacts: { 'prestige-orientation': 0.8, 'space-sensitivity': -0.5 },
      },
      {
        label: 'The space. I\'ll let the address grow on me.',
        impacts: { 'prestige-orientation': -0.7, 'space-sensitivity': 0.6 },
      },
    ],
  },
  {
    id: 'family-horizon',
    kind: 'forced_choice',
    prompt: 'Are kids in the picture, either already or within a 5-year horizon?',
    choices: [
      { label: 'Yes. Kids are part of the household or plan.', impacts: { 'family-trajectory': 0.8, 'space-sensitivity': 0.4 } },
      { label: 'Maybe. Keeping that option open.', impacts: { 'family-trajectory': 0.2 } },
      { label: 'Probably not, or not in this window.', impacts: { 'family-trajectory': -0.7 } },
    ],
  },
  {
    id: 'cultural-anchor',
    kind: 'forced_choice',
    prompt: 'How important is having culturally familiar food, community, or language access in your daily life?',
    choices: [
      { label: 'Essential. I want it in daily reach.', impacts: { 'cultural-ecosystem': 0.8 } },
      { label: 'Nice but not necessary', impacts: { 'cultural-ecosystem': 0.2 } },
      { label: 'Not really a factor', impacts: { 'cultural-ecosystem': -0.5 } },
    ],
  },
  {
    id: 'cultural-communities',
    kind: 'multi_select',
    prompt: 'Which communities, if any, do you want close to home?',
    helperText: 'Mix of ethnic, identity, and religious. Pick none, one, or several. Each pick boosts matching neighborhoods. (Skip if it doesn\'t apply.)',
    options: [
      { value: 'east-asian', label: 'East Asian (Chinese, Korean, Japanese, Taiwanese)' },
      { value: 'south-asian', label: 'South Asian (Indian, Pakistani, Bangladeshi, Sri Lankan)' },
      { value: 'latin-american', label: 'Latin American (Mexican, Dominican, Puerto Rican, Colombian, Ecuadorian)' },
      { value: 'caribbean', label: 'Caribbean (Jamaican, Haitian, Trinidadian)' },
      { value: 'middle-eastern', label: 'Middle Eastern (Arab, Persian, Turkish, Israeli)' },
      { value: 'mediterranean', label: 'Mediterranean (Greek, Italian)' },
      { value: 'eastern-european', label: 'Eastern European (Russian, Polish, Ukrainian)' },
      { value: 'jewish', label: 'Jewish community (Orthodox, Reform)' },
      { value: 'african-american', label: 'African American' },
      { value: 'west-african', label: 'West African (Senegalese, Nigerian)' },
      { value: 'lgbtq', label: 'LGBTQ+ community' },
    ],
    dimensionImpactPerSelection: { 'cultural-ecosystem': 0.15 },
  },
  {
    id: 'creative-immersion',
    kind: 'forced_choice',
    prompt: 'Do you want to live immersed in ambitious or creative scenes, or have access to them without being surrounded?',
    choices: [
      { label: 'Immersed. I want to bump into people doing things.', impacts: { 'creative-energy': 0.8, 'urban-intensity-tolerance': 0.3 } },
      { label: 'Access without immersion', impacts: { 'creative-energy': 0.1 } },
      { label: 'Calm distance. I want to wind down at home.', impacts: { 'creative-energy': -0.6, 'friction-sensitivity': 0.4 } },
    ],
  },
  {
    id: 'noise-tolerance',
    kind: 'forced_choice',
    prompt: 'Two apartments, same price, same size. One is on a quiet block. One is above a busy street. Which?',
    choices: [
      { label: 'The quiet one, no contest', impacts: { 'friction-sensitivity': 0.7 } },
      { label: 'The busy one. I like the energy.', impacts: { 'friction-sensitivity': -0.6 } },
      { label: 'Depends on the day', impacts: { 'friction-sensitivity': 0.0 } },
    ],
  },
  {
    id: 'commute-personality',
    kind: 'forced_choice',
    prompt: 'How does your commute affect your day?',
    choices: [
      { label: 'It needs to be smooth. Friction here ruins everything else.', impacts: { 'transit-psychology': 0.6, 'friction-sensitivity': 0.5 } },
      { label: 'I tune it out. Fine as long as it\'s not crazy.', impacts: { 'transit-psychology': -0.2 } },
      { label: 'I work from home, so it\'s rarely a factor', impacts: { 'space-sensitivity': 0.3 } },
    ],
  },
  {
    id: 'weekend-life',
    kind: 'forced_choice',
    prompt: 'On a typical Saturday, where are you?',
    choices: [
      { label: 'Walking the neighborhood, slow morning at home', impacts: { 'urban-intensity-tolerance': -0.3, 'friction-sensitivity': 0.3 } },
      { label: 'In the city. Restaurants, shows, plans with friends.', impacts: { 'urban-intensity-tolerance': 0.4, 'creative-energy': 0.3 } },
      { label: 'Out of the city. Parks, hikes, the beach.', impacts: { 'environmental-openness': 0.5 } },
    ],
  },
  {
    id: 'apartment-size-feel',
    kind: 'forced_choice',
    prompt: 'Smaller place in your dream area, or meaningfully more space 20 minutes farther out?',
    choices: [
      { label: 'Smaller place. I\'d rather be in the right area.', impacts: { 'space-sensitivity': -0.5 } },
      { label: 'More space. It changes how I live day-to-day.', impacts: { 'space-sensitivity': 0.7 } },
    ],
  },
  {
    id: 'friction-tolerance',
    kind: 'slider',
    prompt: 'Loud, crowded, hectic streets wear me down over time.',
    lowLabel: 'They don\'t bother me',
    highLabel: 'They wear me down',
    dimensionId: 'friction-sensitivity',
  },
  {
    id: 'green-need',
    kind: 'forced_choice',
    prompt: 'Five-minute walk to a real park, or five-minute walk to restaurants and bars. Same building quality. Which weighs more?',
    choices: [
      { label: 'The park. Green close by isn\'t optional.', impacts: { 'environmental-openness': 0.7 } },
      { label: 'Restaurants and bars. Nature can be a 20-minute trip.', impacts: { 'environmental-openness': -0.5 } },
      { label: 'Both matter. I\'d want them close.', impacts: { 'environmental-openness': 0.2 } },
    ],
  },
  {
    id: 'safety-need',
    kind: 'slider',
    prompt: 'I need to feel safe walking home alone late at night.',
    lowLabel: 'Not a strong factor',
    highLabel: 'Essential',
    dimensionId: 'safety-need',
  },
  {
    id: 'school-need',
    kind: 'slider',
    prompt: 'Top-rated zoned public schools are essential to where I\'ll live.',
    lowLabel: 'Not a factor',
    highLabel: 'Required',
    dimensionId: 'school-quality',
  },
  {
    id: 'commute-target',
    kind: 'multi_select',
    purpose: 'commute_targets',
    prompt: 'Where will you actually need to be? Pick all that apply, including a partner\'s office if you\'re a couple.',
    helperText: 'We\'ll weight neighborhoods by realistic door-to-door commute, not by generic transit access. Pick "Mostly remote" if commute isn\'t a constraint.',
    options: [
      { value: 'midtown', label: 'Midtown Manhattan (Grand Central / Penn / Bryant Park)' },
      { value: 'fidi', label: 'Financial District / Lower Manhattan' },
      { value: 'hudson-yards', label: 'Hudson Yards / West Chelsea' },
      { value: 'lic', label: 'Long Island City / Court Square' },
      { value: 'downtown-brooklyn', label: 'Downtown Brooklyn / DUMBO' },
      { value: 'newport-jc', label: 'Jersey City (Newport / Exchange Place)' },
      { value: 'stamford', label: 'Stamford CT' },
      { value: 'greenwich', label: 'Greenwich CT' },
      { value: 'westport', label: 'Westport CT' },
      { value: 'remote', label: 'Mostly remote. Occasional touchdown is fine.' },
      { value: 'other', label: 'Somewhere else (we\'ll skip commute scoring)' },
    ],
  },
  {
    id: 'commute-tolerance',
    kind: 'multi_select',
    purpose: 'commute_tolerance',
    prompt: 'How much door-to-door commute can you live with on a typical day?',
    options: [
      { value: '30', label: 'Under 30 min. Anything more drains me.' },
      { value: '45', label: '30–45 min. Pretty standard NYC commute.' },
      { value: '60', label: '45–60 min. Fine if the neighborhood is right.' },
      { value: '90', label: '60+ min. Willing to trade for what I want.' },
    ],
  },
  {
    id: 'must-haves',
    kind: 'multi_select',
    purpose: 'must_haves',
    prompt: 'Last one. Anything you truly will not compromise on?',
    helperText: 'Hard filters. Pick anything that\'s genuinely non-negotiable. Anything you don\'t pick is treated as a soft preference. (Skip if nothing applies.)',
    options: [
      { value: 'subway-redundancy', label: 'Multiple transit options (any mix of subway, PATH, ferry, rail, express bus)' },
      { value: 'walking-distance-park', label: 'Walking distance to a major park or waterfront' },
      { value: 'house-or-townhouse', label: 'Single-family homes or townhouses available' },
      { value: 'luxury-highrise', label: 'Newer luxury high-rise (doorman, gym, modern fixtures)' },
      { value: 'top-schools', label: 'Top-rated zoned public schools' },
      { value: 'quiet-blocks-available', label: 'A quiet residential block, even if the neighborhood is busy' },
      { value: 'family-infrastructure', label: 'Strong family-life infrastructure (playgrounds, kid-friendly streets, other families nearby)' },
      { value: 'no-car', label: 'Don\'t need a car for daily life' },
      { value: 'cultural-match', label: 'Cultural-community match (uses your earlier picks)' },
    ],
  },
] as const;
