import type { Question } from './types';

export const questions: readonly Question[] = [
  {
    id: 'commute-target',
    kind: 'multi_select',
    purpose: 'commute_targets',
    prompt: 'Where will you actually need to be? Pick all that apply, including a partner\'s office if you\'re a couple.',
    helperText: 'We\'ll weight neighborhoods by realistic door-to-door commute, not just generic transit. Pick "Mostly remote" if commute isn\'t a constraint.',
    options: [
      { value: 'midtown', label: 'Midtown Manhattan (Grand Central / Penn / Bryant Park)' },
      { value: 'fidi', label: 'Financial District / Lower Manhattan' },
      { value: 'hudson-yards', label: 'Hudson Yards / Chelsea West' },
      { value: 'lic', label: 'Long Island City / Court Square' },
      { value: 'downtown-brooklyn', label: 'Downtown Brooklyn / DUMBO' },
      { value: 'newport-jc', label: 'Jersey City (Newport / Exchange Place)' },
      { value: 'stamford', label: 'Stamford CT' },
      { value: 'greenwich', label: 'Greenwich CT' },
      { value: 'westport', label: 'Westport CT' },
      { value: 'remote', label: 'Mostly remote — occasional touchdown is fine' },
      { value: 'other', label: 'Somewhere else (we\'ll skip commute scoring)' },
    ],
  },
  {
    id: 'commute-tolerance',
    kind: 'multi_select',
    purpose: 'commute_tolerance',
    prompt: 'How much door-to-door commute can you live with on a typical day?',
    helperText: 'Pick one. We\'ll use it to weight neighborhoods against your office cluster(s).',
    options: [
      { value: '30', label: 'Under 30 min — anything more drains me' },
      { value: '45', label: '30-45 min — pretty standard NYC commute' },
      { value: '60', label: '45-60 min — fine if the neighborhood is right' },
      { value: '90', label: '60+ min — willing to trade for what I want' },
    ],
  },
  {
    id: 'transit-redundancy',
    kind: 'forced_choice',
    prompt: 'Two neighborhoods, all else equal. One has a single transit option — one subway line, OR one ferry, OR one rail line. The other has multiple. Which fits you?',
    choices: [
      { label: 'Multiple options. I\'d take the redundancy.', impacts: { 'transit-psychology': 0.7 } },
      { label: 'Single option. Simpler is better.', impacts: { 'transit-psychology': -0.5 } },
    ],
  },
  {
    id: 'prestige-vs-space',
    kind: 'forced_choice',
    prompt: 'Smaller apartment in a famous neighborhood, or materially more space in a less-known one?',
    choices: [
      {
        label: 'The famous neighborhood. The address matters.',
        impacts: { 'prestige-orientation': 0.8, 'space-sensitivity': -0.5 },
      },
      {
        label: 'The space. I\'ll let the address grow on me.',
        impacts: { 'prestige-orientation': -0.7, 'space-sensitivity': 0.6 },
      },
    ],
  },
  {
    id: 'family-horizon',
    kind: 'forced_choice',
    prompt: 'Are kids in the picture — already raising them, or in a 5-year horizon?',
    choices: [
      { label: 'Yes. Kids are part of the plan.', impacts: { 'family-trajectory': 0.8, 'space-sensitivity': 0.4 } },
      { label: 'Probably not, or not in this window.', impacts: { 'family-trajectory': -0.7 } },
      { label: 'Considering it.', impacts: { 'family-trajectory': 0.2 } },
    ],
  },
  {
    id: 'cultural-anchor',
    kind: 'forced_choice',
    prompt: 'How important is having culturally familiar food, community, or language access in your daily life?',
    choices: [
      { label: 'Essential. I want to feel at home.', impacts: { 'cultural-ecosystem': 0.8 } },
      { label: 'Nice but not necessary', impacts: { 'cultural-ecosystem': 0.2 } },
      { label: 'Not really a factor', impacts: { 'cultural-ecosystem': -0.5 } },
    ],
  },
  {
    id: 'cultural-communities',
    kind: 'multi_select',
    prompt: 'Which cultural communities, if any, do you want to live near?',
    helperText: 'Pick none, one, or several. Each pick gives matching neighborhoods a stronger boost. (You can skip this if it doesn\'t apply.)',
    options: [
      { value: 'east-asian', label: 'East Asian (Chinese, Korean, Japanese, Taiwanese)' },
      { value: 'south-asian', label: 'South Asian (Indian, Pakistani, Bangladeshi, Sri Lankan)' },
      { value: 'latin-american', label: 'Latin American (Mexican, Dominican, Puerto Rican, Colombian, Ecuadorian)' },
      { value: 'caribbean', label: 'Caribbean (Jamaican, Haitian, Trinidadian)' },
      { value: 'middle-eastern', label: 'Middle Eastern (Arab, Persian, Turkish, Israeli)' },
      { value: 'mediterranean', label: 'Mediterranean (Greek, Italian)' },
      { value: 'eastern-european', label: 'Eastern European (Russian, Polish, Ukrainian)' },
      { value: 'jewish', label: 'Jewish community (Orthodox, Reform)' },
      { value: 'african-american', label: 'African American' },
      { value: 'west-african', label: 'West African (Senegalese, Nigerian)' },
      { value: 'lgbtq', label: 'LGBTQ+ community' },
    ],
    dimensionImpactPerSelection: { 'cultural-ecosystem': 0.15 },
  },
  {
    id: 'creative-immersion',
    kind: 'forced_choice',
    prompt: 'Do you want to live immersed in ambitious or creative scenes, or have access to them without being surrounded?',
    choices: [
      { label: 'Immersed. I want to bump into people doing things.', impacts: { 'creative-energy': 0.8, 'urban-intensity-tolerance': 0.3 } },
      { label: 'Access without immersion', impacts: { 'creative-energy': 0.1 } },
      { label: 'Calm distance. I want to rest, not perform.', impacts: { 'creative-energy': -0.6, 'friction-sensitivity': 0.4 } },
    ],
  },
  {
    id: 'noise-tolerance',
    kind: 'forced_choice',
    prompt: 'Two apartments, same price, same size. One is on a quiet block. One is above a busy street. Which?',
    choices: [
      { label: 'The quiet one, no contest', impacts: { 'friction-sensitivity': 0.7 } },
      { label: 'The busy one. I like the energy.', impacts: { 'friction-sensitivity': -0.6 } },
      { label: 'Depends on the day', impacts: { 'friction-sensitivity': 0.0 } },
    ],
  },
  {
    id: 'commute-personality',
    kind: 'forced_choice',
    prompt: 'How does your commute affect your day?',
    choices: [
      { label: 'It needs to be smooth. Friction here ruins everything else.', impacts: { 'transit-psychology': 0.6, 'friction-sensitivity': 0.5 } },
      { label: 'I tune it out. Fine as long as it\'s not crazy.', impacts: { 'transit-psychology': -0.2 } },
      { label: 'I work from home, so it\'s rarely a factor', impacts: { 'transit-psychology': -0.3, 'space-sensitivity': 0.3 } },
    ],
  },
  {
    id: 'weekend-life',
    kind: 'forced_choice',
    prompt: 'On a typical Saturday, where are you?',
    choices: [
      { label: 'Walking the neighborhood, slow morning at home', impacts: { 'urban-intensity-tolerance': -0.3, 'friction-sensitivity': 0.3 } },
      { label: 'In the city. Restaurants, shows, plans with friends.', impacts: { 'urban-intensity-tolerance': 0.4, 'creative-energy': 0.3 } },
      { label: 'Out of the city. Parks, hikes, the beach.', impacts: { 'environmental-openness': 0.5 } },
    ],
  },
  {
    id: 'apartment-size-feel',
    kind: 'slider',
    prompt: 'Apartment size strongly affects how I feel about my life.',
    lowLabel: 'I\'m happy in small spaces',
    highLabel: 'I need real space',
    dimensionId: 'space-sensitivity',
  },
  {
    id: 'friction-tolerance',
    kind: 'slider',
    prompt: 'Chaotic, gritty, high-friction daily environments drain me over time.',
    lowLabel: 'They don\'t bother me',
    highLabel: 'They drain me',
    dimensionId: 'friction-sensitivity',
  },
  {
    id: 'green-need',
    kind: 'slider',
    prompt: 'Regular access to parks, water, or nature is essential to my wellbeing.',
    lowLabel: 'Don\'t really need it',
    highLabel: 'Essential',
    dimensionId: 'environmental-openness',
  },
  {
    id: 'safety-need',
    kind: 'slider',
    prompt: 'I need to feel safe walking home alone late at night.',
    lowLabel: 'Not a strong factor',
    highLabel: 'Essential',
    dimensionId: 'safety-need',
  },
  {
    id: 'school-need',
    kind: 'slider',
    prompt: 'Top-rated zoned public schools are essential to where I\'ll live.',
    lowLabel: 'Not a factor',
    highLabel: 'Required',
    dimensionId: 'school-quality',
  },
  {
    id: 'must-haves',
    kind: 'multi_select',
    purpose: 'must_haves',
    prompt: 'Last one. Anything you truly will not compromise on?',
    helperText: 'Hard filters. Pick anything that\'s genuinely non-negotiable. Anything you don\'t pick is treated as a soft preference. (Skip if nothing applies.)',
    options: [
      { value: 'subway-redundancy', label: 'Multiple transit options (any mix of subway, PATH, ferry, rail, express bus)' },
      { value: 'walking-distance-park', label: 'Walking distance to a major park or waterfront' },
      { value: 'house-or-townhouse', label: 'Single-family homes or townhouses available' },
      { value: 'luxury-highrise', label: 'Newer luxury high-rise (doorman, gym, modern fixtures)' },
      { value: 'top-schools', label: 'Top-rated zoned public schools' },
      { value: 'calm-blocks', label: 'Calm overall — whole neighborhood is low-friction' },
      { value: 'quiet-blocks-available', label: 'A quiet residential block available, even if the neighborhood is busy' },
      { value: 'no-car', label: 'Don\'t need a car for daily life' },
      { value: 'cultural-match', label: 'Cultural-community match (uses your earlier picks)' },
    ],
  },
] as const;
