import type { Question } from './types';

export const questions: readonly Question[] = [
  {
    id: 'home-feel',
    kind: 'forced_choice',
    prompt: 'When you picture coming home at the end of a long day, what do you most want?',
    choices: [
      {
        label: 'A quiet block where you can decompress',
        impacts: { 'urban-intensity-tolerance': -0.7, 'friction-sensitivity': 0.5, 'environmental-openness': 0.3 },
      },
      {
        label: 'Energy and movement so the city pulls you back out',
        impacts: { 'urban-intensity-tolerance': 0.7, 'friction-sensitivity': -0.4, 'creative-energy': 0.3 },
      },
    ],
  },
  {
    id: 'transit-redundancy',
    kind: 'forced_choice',
    prompt: 'Would relying on a single subway line for daily life frustrate you over time?',
    choices: [
      { label: 'Yes, I need options', impacts: { 'transit-psychology': 0.7 } },
      { label: 'Not really, one good line is enough', impacts: { 'transit-psychology': -0.5 } },
    ],
  },
  {
    id: 'prestige-vs-space',
    kind: 'forced_choice',
    prompt: 'Smaller apartment in a famous neighborhood, or materially more space in a less-known one?',
    choices: [
      {
        label: 'The famous neighborhood. The address matters.',
        impacts: { 'prestige-orientation': 0.8, 'space-sensitivity': -0.5 },
      },
      {
        label: 'The space. I\'ll let the address grow on me.',
        impacts: { 'prestige-orientation': -0.7, 'space-sensitivity': 0.6 },
      },
    ],
  },
  {
    id: 'family-horizon',
    kind: 'forced_choice',
    prompt: 'Are you optimizing for the life you have today, or the one you might have in five years?',
    choices: [
      { label: 'Today. Five years is a long time.', impacts: { 'family-trajectory': -0.7, 'creative-energy': 0.3 } },
      { label: 'Five years. I want to put down roots.', impacts: { 'family-trajectory': 0.8, 'space-sensitivity': 0.4 } },
      { label: 'A bit of both. I\'m thinking about the next 2 to 3 years.', impacts: { 'family-trajectory': 0.2 } },
    ],
  },
  {
    id: 'cultural-anchor',
    kind: 'forced_choice',
    prompt: 'How important is having culturally familiar food, community, or language access in your daily life?',
    choices: [
      { label: 'Essential. I want to feel at home.', impacts: { 'cultural-ecosystem': 0.8 } },
      { label: 'Nice but not necessary', impacts: { 'cultural-ecosystem': 0.2 } },
      { label: 'Not really a factor', impacts: { 'cultural-ecosystem': -0.5 } },
    ],
  },
  {
    id: 'cultural-communities',
    kind: 'multi_select',
    prompt: 'Which cultural communities, if any, do you want to live near?',
    helperText: 'Pick none, one, or several. Each pick gives matching neighborhoods a stronger boost. (You can skip this if it doesn\'t apply.)',
    options: [
      { value: 'east-asian', label: 'East Asian (Chinese, Korean, Japanese, Taiwanese)' },
      { value: 'south-asian', label: 'South Asian (Indian, Pakistani, Bangladeshi, Sri Lankan)' },
      { value: 'latin-american', label: 'Latin American (Mexican, Dominican, Puerto Rican, Colombian, Ecuadorian)' },
      { value: 'caribbean', label: 'Caribbean (Jamaican, Haitian, Trinidadian)' },
      { value: 'middle-eastern', label: 'Middle Eastern (Arab, Persian, Turkish, Israeli)' },
      { value: 'mediterranean', label: 'Mediterranean (Greek, Italian)' },
      { value: 'eastern-european', label: 'Eastern European (Russian, Polish, Ukrainian)' },
      { value: 'jewish', label: 'Jewish community (Orthodox, Reform)' },
      { value: 'african-american', label: 'African American' },
      { value: 'west-african', label: 'West African (Senegalese, Nigerian)' },
      { value: 'lgbtq', label: 'LGBTQ+ community' },
    ],
    dimensionImpactPerSelection: { 'cultural-ecosystem': 0.15 },
  },
  {
    id: 'park-need',
    kind: 'forced_choice',
    prompt: 'Do parks and waterfronts materially affect your mood?',
    choices: [
      { label: 'Yes. I notice when I haven\'t had nature in a while.', impacts: { 'environmental-openness': 0.8 } },
      { label: 'I like them but don\'t need them daily', impacts: { 'environmental-openness': 0.0 } },
      { label: 'Honestly, not much', impacts: { 'environmental-openness': -0.6 } },
    ],
  },
  {
    id: 'creative-immersion',
    kind: 'forced_choice',
    prompt: 'Do you want to live immersed in ambitious or creative scenes, or have access to them without being surrounded?',
    choices: [
      { label: 'Immersed. I want to bump into people doing things.', impacts: { 'creative-energy': 0.8, 'urban-intensity-tolerance': 0.3 } },
      { label: 'Access without immersion', impacts: { 'creative-energy': 0.1 } },
      { label: 'Calm distance. I want to rest, not perform.', impacts: { 'creative-energy': -0.6, 'friction-sensitivity': 0.4 } },
    ],
  },
  {
    id: 'noise-tolerance',
    kind: 'forced_choice',
    prompt: 'Two apartments, same price, same size. One is on a quiet block. One is above a busy street. Which?',
    choices: [
      { label: 'The quiet one, no contest', impacts: { 'friction-sensitivity': 0.7 } },
      { label: 'The busy one. I like the energy.', impacts: { 'friction-sensitivity': -0.6 } },
      { label: 'Depends on the day', impacts: { 'friction-sensitivity': 0.0 } },
    ],
  },
  {
    id: 'commute-personality',
    kind: 'forced_choice',
    prompt: 'How does your commute affect your day?',
    choices: [
      { label: 'It needs to be smooth. Friction here ruins everything else.', impacts: { 'transit-psychology': 0.6, 'friction-sensitivity': 0.5 } },
      { label: 'I tune it out. Fine as long as it\'s not crazy.', impacts: { 'transit-psychology': -0.2 } },
      { label: 'I work from home, so it\'s rarely a factor', impacts: { 'transit-psychology': -0.3, 'space-sensitivity': 0.3 } },
    ],
  },
  {
    id: 'weekend-life',
    kind: 'forced_choice',
    prompt: 'On a typical Saturday, where are you?',
    choices: [
      { label: 'Walking the neighborhood, slow morning at home', impacts: { 'urban-intensity-tolerance': -0.3, 'friction-sensitivity': 0.3 } },
      { label: 'In the city. Restaurants, shows, plans with friends.', impacts: { 'urban-intensity-tolerance': 0.4, 'creative-energy': 0.3 } },
      { label: 'Out of the city. Parks, hikes, the beach.', impacts: { 'environmental-openness': 0.5 } },
    ],
  },
  {
    id: 'aspirational-vs-grounded',
    kind: 'forced_choice',
    prompt: 'When you talk about where you live, do you feel proud of the name, or proud of the place itself?',
    choices: [
      { label: 'The name. It\'s part of how I think about myself.', impacts: { 'prestige-orientation': 0.7 } },
      { label: 'The place. I\'d rather under-promise and over-deliver.', impacts: { 'prestige-orientation': -0.6 } },
    ],
  },
  {
    id: 'apartment-size-feel',
    kind: 'slider',
    prompt: 'Apartment size strongly affects how I feel about my life.',
    lowLabel: 'I\'m happy in small spaces',
    highLabel: 'I need real space',
    dimensionId: 'space-sensitivity',
  },
  {
    id: 'friction-tolerance',
    kind: 'slider',
    prompt: 'Chaotic, gritty, high-friction daily environments drain me over time.',
    lowLabel: 'They don\'t bother me',
    highLabel: 'They drain me',
    dimensionId: 'friction-sensitivity',
  },
  {
    id: 'green-need',
    kind: 'slider',
    prompt: 'Regular access to parks, water, or nature is essential to my wellbeing.',
    lowLabel: 'Don\'t really need it',
    highLabel: 'Essential',
    dimensionId: 'environmental-openness',
  },
  {
    id: 'safety-need',
    kind: 'slider',
    prompt: 'I need to feel safe walking home alone late at night.',
    lowLabel: 'Not a strong factor',
    highLabel: 'Essential',
    dimensionId: 'safety-need',
  },
  {
    id: 'school-need',
    kind: 'slider',
    prompt: 'Top-rated zoned public schools are essential to where I\'ll live.',
    lowLabel: 'Not a factor',
    highLabel: 'Required',
    dimensionId: 'school-quality',
  },
  {
    id: 'must-haves',
    kind: 'multi_select',
    purpose: 'must_haves',
    prompt: 'Last one. Anything you truly will not compromise on?',
    helperText: 'Hard filters. Pick anything that\'s genuinely non-negotiable. Anything you don\'t pick is treated as a soft preference. (Skip if nothing applies.)',
    options: [
      { value: 'subway-redundancy', label: 'Multiple transit options (any mix of subway, PATH, ferry, rail, express bus)' },
      { value: 'walking-distance-park', label: 'Walking distance to a major park or waterfront' },
      { value: 'house-or-townhouse', label: 'Single-family homes or townhouses available' },
      { value: 'luxury-highrise', label: 'Newer luxury high-rise (doorman, gym, modern fixtures)' },
      { value: 'top-schools', label: 'Top-rated zoned public schools' },
      { value: 'calm-blocks', label: 'Calm, low-friction blocks' },
      { value: 'quiet-blocks-available', label: 'Notable quiet residential enclaves (refuge from busy streets)' },
      { value: 'no-car', label: 'Don\'t need a car for daily life' },
      { value: 'cultural-match', label: 'Cultural-community match (uses your earlier picks)' },
    ],
  },
] as const;
